package view.responses;

public enum CardEffectsResponses {
    INVALID_CELL_NUMBER,
    PLEASE_SELECT_A_VALID_NUMBER,
    PLEASE_SELECT_MONSTER,
    PLEASE_SELECT_A_VALID_MONSTER,
    PLEASE_SELECT_LEVEL_7_OR_MORE,
    MONSTER_ZONE_IS_FULL,
    PLEASE_SELECT_AN_SPELL,
    PLEASE_SELECT_A_FIELD_SPELL,
    PLEASE_SELECT_A_VALID_TYPE,
    YOU_DONT_HAVE_ANY_FIELD_SPELL,
    NO_MONSTERS,
    CANT_RITUAL_SUMMON,
    SPECIAL_SUMMON_NOW,
    HAVE_NO_CARDS,
    CANT_ACTIVATE_TRAP

}
