package view.responses;

public enum DeckMenuResponses {
    SUCCESSFUL,
    DECK_ALREADY_EXISTS,
    DECK_DOESNT_EXIST,
    CARD_DOESNT_EXIST,
    MAIN_DECK_IS_FULL,
    SIDE_DECK_IS_FULL,
    CANT_ADD_MORE_OF_THIS_CARD,
    CURRENT_MENU_DECK_MENU,
    INVALID_COMMAND,
}
