package view.responses;

public enum LoginMenuResponses {
    USER_WITH_THIS_NICKNAME_EXITS,
    USER_WITH_THIS_USERNAME_EXITS,
    USER_LOGIN_SUCCESSFUL,
    USER_CREATED_SUCCESSFULLY,
    PASSWORD_AND_USERNAME_DIDNT_MATCH,
    THERE_IS_NOT_A_USER_WITH_THIS_USERNAME,
    CURRENT_MENU_LOGIN_MENU,
    INVALID_COMMAND,
    PLEASE_FILL_ALL_OF_THE_FIELDS, PASSWORDS_DIDNT_MATCH;
}
