package view.responses;

public enum ProfileMenuResponses {
        NICKNAME_CHANGED_SUCCESSFULLY,
        USER_WITH_NICKNAME_ALREADY_EXISTS,
        PASSWORD_CHANGED_SUCCESSFULLY,
        CURRENT_PASSWORD_IS_INVALID,
        PLEASE_ENTER_A_NEW_PASSWORD,
        INVALID_COMMAND,
        CURRENT_MENU_PROFILE_MENU
        }
