package view.responses;

public enum StartingGameResponses {
    THERE_IS_NO_PLAYER_WITH_THIS_USERNAME,
    INVALID_COMMAND,
    CURRENT_MENU_DUEL_MENU,
    NUMBER_OF_ROUNDS_IS_NOT_SUPPORTED,
    DIFFICULTY_IS_NOT_SUPPORTED,

}
